### ISSUE TITLE
Build Failed!

### ISSUE THREAD

**Issue by chokri** [brewfactory/BrewMobile#22]
Hi I just followed the readme file but it told me that the build is failed :( 
 carthage bootstrap
*** Cloning SIOSocket
*** Checking out SIOSocket at "749c697df752ae81ae7aeff79de917f2981a6590"
*** Cloning iso-8601-date-formatter
*** Checking out iso-8601-date-formatter at "103ee049f0ce2fd66b16b814adbc6b741959ce64"
*** xcodebuild output can be found in /var/folders/d5/f4g1kfpn76l302dbxx__v8cc0000gn/T/carthage-xcodebuild.sXuuSj.log
*** Building scheme "SocketIOFramework" in SocketIO.xcodeproj
** BUILD FAILED **

**Comment by vasarhelyia** [comment]
Carthage requires a valid code signing identity, see: https://github.com/Carthage/Carthage/issues/235.

**Comment by vasarhelyia** [comment]
Ok, I created a [pull request](https://github.com/brewfactory/BrewMobile/pull/23) with a post build script to resign the application with no identity. You just have to set the `SIMULATOR_ONLY` preprocessor flag to **1** in the target build settings. Please try it out and let me know how it went.

**Comment by vasarhelyia** [comment]
Closing, [you need code signing identity for using Carthage](https://github.com/Carthage/Carthage/issues/235).
